"""
PostgreSQL ORM models for Document Portal.

Tables:
    chat_sessions   — one row per user/upload session
    chat_history    — per-turn message log per session
    query_audit_log — every query + response + token/latency metadata
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker

# ---------------------------------------------------------------------------
# Engine + session factory
# ---------------------------------------------------------------------------

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:postgres@localhost:5432/document_portal",
)

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,   # recycle stale connections automatically
    pool_size=5,
    max_overflow=10,
)

SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# chat_sessions
# ---------------------------------------------------------------------------

class ChatSession(Base):
    """
    One row per document-chat session.

    session_id  matches the UUID already generated by generate_session_id().
    status      is 'active' while the RAG instance lives in memory, 'expired'
                after eviction (future TTL cleanup job can set this).
    """
    __tablename__ = "chat_sessions"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    session_id  = Column(String(128), unique=True, nullable=False, index=True)
    created_at  = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    last_active = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                         onupdate=lambda: datetime.now(timezone.utc))
    status      = Column(String(32), default="active")   # active | expired
    file_names  = Column(Text, default="")               # comma-joined original filenames
    chunk_size  = Column(Integer, default=400)
    chunk_overlap = Column(Integer, default=50)
    k           = Column(Integer, default=3)


# ---------------------------------------------------------------------------
# chat_history
# ---------------------------------------------------------------------------

class ChatMessage(Base):
    """
    Individual turns within a chat session.

    role    is 'user' or 'assistant' (mirrors OpenAI / LangChain convention).
    """
    __tablename__ = "chat_history"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    session_id  = Column(String(128), nullable=False, index=True)
    role        = Column(String(16), nullable=False)   # user | assistant
    content     = Column(Text, nullable=False)
    created_at  = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# query_audit_log
# ---------------------------------------------------------------------------

class QueryAuditLog(Base):
    """
    Immutable record of every RAG query and its response.

    Stores enough metadata to reconstruct cost/performance reports:
      - latency_ms     wall-clock time for the full chain
      - prompt_tokens  / completion_tokens — forwarded from LangFuse if available
      - pii_redacted   flag: True if Presidio stripped anything before the LLM call
    """
    __tablename__ = "query_audit_log"

    id                = Column(Integer, primary_key=True, autoincrement=True)
    session_id        = Column(String(128), nullable=False, index=True)
    question          = Column(Text, nullable=False)
    answer            = Column(Text)
    latency_ms        = Column(Float)
    prompt_tokens     = Column(Integer)
    completion_tokens = Column(Integer)
    k_used            = Column(Integer)
    pii_redacted      = Column(Integer, default=0)   # count of PII entities stripped
    created_at        = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# DDL helper — call once at startup
# ---------------------------------------------------------------------------

def create_all_tables() -> None:
    """Create all tables if they don't already exist (idempotent)."""
    Base.metadata.create_all(bind=engine)
